# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/minized_DO_NOT_EDIT.xdc

# Block Designs: bd/ZyncPS_ClockGen/ZyncPS_ClockGen.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyncPS_ClockGen || ORIG_REF_NAME==ZyncPS_ClockGen} -quiet] -quiet

# IP: bd/ZyncPS_ClockGen/ip/ZyncPS_ClockGen_processing_system7_0_0/ZyncPS_ClockGen_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyncPS_ClockGen_processing_system7_0_0 || ORIG_REF_NAME==ZyncPS_ClockGen_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZyncPS_ClockGen/ip/ZyncPS_ClockGen_c_counter_binary_0_0/ZyncPS_ClockGen_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyncPS_ClockGen_c_counter_binary_0_0 || ORIG_REF_NAME==ZyncPS_ClockGen_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/ZyncPS_ClockGen/ip/ZyncPS_ClockGen_xlslice_0_0/ZyncPS_ClockGen_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyncPS_ClockGen_xlslice_0_0 || ORIG_REF_NAME==ZyncPS_ClockGen_xlslice_0_0} -quiet] -quiet

# IP: bd/ZyncPS_ClockGen/ip/ZyncPS_ClockGen_Toplevel_Impl_0_0/ZyncPS_ClockGen_Toplevel_Impl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyncPS_ClockGen_Toplevel_Impl_0_0 || ORIG_REF_NAME==ZyncPS_ClockGen_Toplevel_Impl_0_0} -quiet] -quiet
